language: python
python:
  - "2.7"
# command to install dependencies
install:
  - "sudo apt-get install python-qt4 python-qt4-dev python-sip python-sip-dev"
  - "pip install -r requirements.txt"
# command to run tests
script: nosetests
virtualenv:
  system_site_packages: true
