language: python
python:
  - "2.7"
# command to install dependencies
install:
  - "sudo apt-get install python-qt4 python-qt4-dev python-sip python-sip-dev"
  - "pip install -r requirements.txt"
# command to run tests
script: nosetests
virtualenv:
  system_site_packages: true

addons:
  sauce_connect:
    username: "amolmandhane"
    access_key:
      secure: "XEAsk+X5v46PK1QJ/U98A9MRARLGb1gqpQZe62Z0lbHJxi99OeWczzgTj3Pix4TDco8H4cOQi5Aocl75tJ8lmZ8jdJvbhCqGT0ANvpZIFMpwA/F8PNdXSCEuqXx6HTlfLqwoGdOb/TWE7Opa55FnGbBcMNID3u1sGMO27I/m8Wg="
