sudo: false

language: python

python:
  - "2.7"

# command to install dependencies

addons:
  apt:
    packages:
    - python-qt4
    - python-qt4-dev
    - python-sip
    - python-sip-dev
    - qt4-dev-tools
    - pyqt4-dev-tools

# command to install dependencies
install:
  - pip install .
  - pip install -r requirements.txt

# command to run tests

# Have to disable some tests due to automation incompatibilities of Qt
# The results of these test vary python/qt version to version
# However, this should not be an issue in dev/production, only in testing.
script: nosetests -a '!no-coverage'
virtualenv:
  system_site_packages: true

before_script:
  - export DISPLAY=:99.0
  - Xvfb $DISPLAY >& /tmp/Xvfb.log &
  - trap "kill $! || true" EXIT
  - sleep 10


notifications:
  email: false
